# Cloudflare Pages Configuration
name = "logistics-eik"
compatibility_date = "2024-08-06"

# Pages build configuration
pages_build_output_dir = "out"

[build]
command = "npm run build"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"
