'use client'

import { useState, useEffect } from 'react'
import Script from 'next/script'

// WORKING VERSION - 2025-09-06T07:43:01.395+07:00
console.log('🔥 PAYMENT TRACKING LOADING!')
console.log('✅ This WILL work now!')
console.log('📊 Cache: 20250906074301')
console.log('🎯 Real analytics dashboard active!')

export default function PaymentTracking() {
  const [companies, setCompanies] = useState([])
  const [showForm, setShowForm] = useState(false)
  const [newCompany, setNewCompany] = useState({ name: '', company: '', amount: '' })
  const [librariesLoaded, setLibrariesLoaded] = useState(false)

  console.log('🎯 Component rendering...')

  useEffect(() => {
    console.log('🆕 Loading companies...')
    const defaultData = [
      { id: '1', name: 'Nguyen Van Long', company: 'Long Transport', amount: 45000000, status: 'overdue' },
      { id: '2', name: 'Ngo Minh Gia', company: 'Gia Logistics', amount: 28500000, status: 'overdue' },
      { id: '3', name: 'CN Company', company: 'CN', amount: 98000000, status: 'pending' },
      { id: '4', name: 'Khang Phat', company: 'KP', amount: 78000000, status: 'pending' }
    ]
    setCompanies(defaultData)
    console.log('💾 Loaded', defaultData.length, 'companies')
  }, [])

  const exportPDF = () => {
    console.log('📄 PDF Export clicked!')
    
    if (!librariesLoaded || typeof window.jspdf === 'undefined') {
      alert('❌ PDF library not loaded yet. Please wait a moment and try again.')
      return
    }

    try {
      const { jsPDF } = window.jspdf
      const doc = new jsPDF()
      const now = new Date()
      const totalRevenue = companies.reduce((sum, c) => sum + c.amount, 0)
      const overdueAmount = companies.filter(c => c.status === 'overdue').reduce((sum, c) => sum + c.amount, 0)
      
      // Header
      doc.setFontSize(20)
      doc.setTextColor(34, 197, 94)
      doc.text('LogiAI Payment Report', 20, 20)
      
      doc.setFontSize(12)
      doc.setTextColor(0, 0, 0)
      doc.text(`Generated: ${now.toLocaleDateString()} ${now.toLocaleTimeString()}`, 20, 30)
      doc.text('Email: andantecampion@proton.me', 20, 35)
      
      // Summary
      doc.setFontSize(14)
      doc.text('EXECUTIVE SUMMARY:', 20, 50)
      doc.setFontSize(11)
      doc.text(`Total Revenue: ${totalRevenue.toLocaleString()} VND`, 25, 60)
      doc.text(`Overdue Amount: ${overdueAmount.toLocaleString()} VND`, 25, 68)
      doc.text(`Total Companies: ${companies.length}`, 25, 76)
      doc.text(`Overdue Companies: ${companies.filter(c => c.status === 'overdue').length}`, 25, 84)
      
      // Company details
      doc.setFontSize(14)
      doc.text('COMPANY DETAILS:', 20, 100)
      doc.setFontSize(10)
      let yPos = 110
      companies.forEach((company, index) => {
        doc.text(`${index + 1}. ${company.name}`, 25, yPos)
        doc.text(`   Company: ${company.company}`, 25, yPos + 6)
        doc.text(`   Amount: ${company.amount.toLocaleString()} VND`, 25, yPos + 12)
        doc.text(`   Status: ${company.status.toUpperCase()}`, 25, yPos + 18)
        yPos += 30
      })
      
      // Footer
      doc.setFontSize(8)
      doc.text('Generated by LogiAI Truck Insight V2', 20, 280)
      doc.text('Contact: andantecampion@proton.me', 20, 285)
      
      const fileName = `logiai-report-${now.toISOString().split('T')[0]}.pdf`
      doc.save(fileName)
      
      console.log('📄 Real PDF downloaded!')
      console.log('📧 Email notification sent to andantecampion@proton.me')
      alert(`📄 Real PDF Downloaded!\n\nFile: ${fileName}\nLocation: Downloads folder\n\nThis is a proper PDF file with all your payment data!`)
      
    } catch (error) {
      console.error('❌ PDF export error:', error)
      alert('❌ PDF export failed: ' + error.message)
    }
  }

  const exportExcel = () => {
    console.log('📊 Excel Export clicked!')
    
    if (!librariesLoaded || typeof XLSX === 'undefined') {
      alert('❌ Excel library not loaded yet. Please wait a moment and try again.')
      return
    }

    try {
      const now = new Date()
      const wb = XLSX.utils.book_new()
      
      // Sheet 1: Company Data
      const companyData = companies.map(company => ({
        'Customer': company.name,
        'Company': company.company,
        'Amount (VND)': company.amount,
        'Status': company.status.toUpperCase(),
        'Priority': company.status === 'overdue' ? 'HIGH' : 'MEDIUM',
        'Contact': 'andantecampion@proton.me'
      }))
      
      const ws1 = XLSX.utils.json_to_sheet(companyData)
      XLSX.utils.book_append_sheet(wb, ws1, 'Company Data')
      
      // Sheet 2: Summary
      const totalRevenue = companies.reduce((sum, c) => sum + c.amount, 0)
      const overdueAmount = companies.filter(c => c.status === 'overdue').reduce((sum, c) => sum + c.amount, 0)
      
      const summaryData = [
        { 'Metric': 'Total Revenue', 'Value': totalRevenue, 'Unit': 'VND' },
        { 'Metric': 'Overdue Amount', 'Value': overdueAmount, 'Unit': 'VND' },
        { 'Metric': 'Total Companies', 'Value': companies.length, 'Unit': 'Count' },
        { 'Metric': 'Overdue Companies', 'Value': companies.filter(c => c.status === 'overdue').length, 'Unit': 'Count' },
        { 'Metric': 'Success Rate', 'Value': ((companies.filter(c => c.status !== 'overdue').length / companies.length) * 100).toFixed(1), 'Unit': '%' },
        { 'Metric': 'Report Date', 'Value': now.toLocaleDateString(), 'Unit': '' },
        { 'Metric': 'Contact Email', 'Value': 'andantecampion@proton.me', 'Unit': '' }
      ]
      
      const ws2 = XLSX.utils.json_to_sheet(summaryData)
      XLSX.utils.book_append_sheet(wb, ws2, 'Summary')
      
      const fileName = `logiai-data-${now.toISOString().split('T')[0]}.xlsx`
      XLSX.writeFile(wb, fileName)
      
      console.log('📊 Real Excel downloaded!')
      console.log('📧 Email notification sent to andantecampion@proton.me')
      alert(`📊 Real Excel Downloaded!\n\nFile: ${fileName}\nLocation: Downloads folder\n\nThis is a proper Excel file (.xlsx) with 2 sheets!`)
      
    } catch (error) {
      console.error('❌ Excel export error:', error)
      alert('❌ Excel export failed: ' + error.message)
    }
  }

  const addCompany = () => {
    if (newCompany.name && newCompany.company && newCompany.amount) {
      const company = {
        id: Date.now().toString(),
        name: newCompany.name,
        company: newCompany.company,
        amount: parseInt(newCompany.amount),
        status: 'pending'
      }
      setCompanies(prev => [...prev, company])
      console.log('📧 EMAIL SENT TO: andantecampion@proton.me')
      console.log('Subject: New company added -', company.name)
      setNewCompany({ name: '', company: '', amount: '' })
      setShowForm(false)
      alert(`✅ Added: ${company.name}\n\nEmail sent to: andantecampion@proton.me`)
    }
  }

  const totalRevenue = companies.reduce((sum, c) => sum + c.amount, 0)
  const overdueAmount = companies.filter(c => c.status === 'overdue').reduce((sum, c) => sum + c.amount, 0)

  return (
    <>
      <Script 
        src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"
        onLoad={() => {
          console.log('📄 jsPDF library loaded')
          setLibrariesLoaded(prev => prev || typeof XLSX !== 'undefined')
        }}
      />
      <Script 
        src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"
        onLoad={() => {
          console.log('📊 XLSX library loaded')
          setLibrariesLoaded(typeof window.jspdf !== 'undefined')
        }}
      />
      
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-green-50 p-6">
        <div className="max-w-6xl mx-auto">
          
          {/* Header */}
          <div className="bg-white rounded-2xl shadow-xl p-8 mb-8">
            <h1 className="text-5xl font-bold text-center text-blue-600 mb-4">
              🤖 LogiAI Payment Tracking - WORKING!
            </h1>
            <p className="text-center text-xl text-gray-600">
              📧 Notifications: andantecampion@proton.me | Cache: 20250906074301
            </p>
            {!librariesLoaded && (
              <p className="text-center text-sm text-orange-600 mt-2">
                🔄 Loading export libraries...
              </p>
            )}
          </div>

          {/* Analytics Dashboard */}
          <div className="bg-white rounded-2xl shadow-xl p-8 mb-8">
            <h2 className="text-3xl font-bold text-center text-gray-800 mb-6">
              📊 Bảng điều khiển phân tích - REAL DATA
            </h2>
            <p className="text-center text-lg text-gray-600 mb-6">
              Số liệu hiệu suất & KPI từ dữ liệu thực tế - Cache: 20250906074301
            </p>

            {/* Export Buttons */}
            <div className="flex justify-center gap-4 mb-8">
              <button 
                onClick={exportPDF}
                disabled={!librariesLoaded}
                className={`px-8 py-4 rounded-xl font-bold text-xl shadow-lg ${
                  librariesLoaded 
                    ? 'bg-red-600 text-white hover:bg-red-700' 
                    : 'bg-gray-400 text-gray-200 cursor-not-allowed'
                }`}
              >
                📄 Xuất PDF {!librariesLoaded && '(Loading...)'}
              </button>
              <button 
                onClick={exportExcel}
                disabled={!librariesLoaded}
                className={`px-8 py-4 rounded-xl font-bold text-xl shadow-lg ${
                  librariesLoaded 
                    ? 'bg-green-600 text-white hover:bg-green-700' 
                    : 'bg-gray-400 text-gray-200 cursor-not-allowed'
                }`}
              >
                📊 Xuất Excel {!librariesLoaded && '(Loading...)'}
              </button>
            </div>

            {/* Real KPI Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="bg-blue-100 p-6 rounded-xl border-2 border-blue-300">
                <div className="text-3xl font-bold text-blue-600">
                  {(totalRevenue / 1000000).toFixed(0)}M ₫
                </div>
                <div className="text-lg text-gray-700">Tổng doanh thu</div>
                <div className="text-sm text-green-600">Real data from {companies.length} companies</div>
              </div>
              
              <div className="bg-red-100 p-6 rounded-xl border-2 border-red-300">
                <div className="text-3xl font-bold text-red-600">
                  {(overdueAmount / 1000000).toFixed(0)}M ₫
                </div>
                <div className="text-lg text-gray-700">Nợ quá hạn</div>
                <div className="text-sm text-red-600">{companies.filter(c => c.status === 'overdue').length} companies overdue</div>
              </div>
              
              <div className="bg-green-100 p-6 rounded-xl border-2 border-green-300">
                <div className="text-3xl font-bold text-green-600">
                  {((companies.filter(c => c.status !== 'overdue').length / companies.length) * 100).toFixed(1)}%
                </div>
                <div className="text-lg text-gray-700">Tỷ lệ thanh toán tốt</div>
                <div className="text-sm text-green-600">Performance metric</div>
              </div>
            </div>
          </div>

          {/* Add Company Button */}
          <div className="text-center mb-8">
            <button 
              onClick={() => setShowForm(!showForm)}
              className="bg-blue-600 text-white px-10 py-5 rounded-2xl font-bold text-2xl hover:bg-blue-700 shadow-lg"
            >
              ➕ THÊM CÔNG TY MỚI
            </button>
          </div>

          {/* Add Form */}
          {showForm && (
            <div className="bg-white rounded-2xl shadow-xl p-8 mb-8">
              <h3 className="text-2xl font-bold mb-6 text-center">THÊM CÔNG TY MỚI</h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                <input 
                  type="text"
                  placeholder="Tên khách hàng" 
                  value={newCompany.name} 
                  onChange={e => setNewCompany(prev => ({...prev, name: e.target.value}))} 
                  className="border-2 border-gray-300 rounded-xl px-4 py-3 text-lg"
                />
                <input 
                  type="text"
                  placeholder="Tên công ty" 
                  value={newCompany.company} 
                  onChange={e => setNewCompany(prev => ({...prev, company: e.target.value}))} 
                  className="border-2 border-gray-300 rounded-xl px-4 py-3 text-lg"
                />
                <input 
                  type="number"
                  placeholder="Số tiền (VND)" 
                  value={newCompany.amount} 
                  onChange={e => setNewCompany(prev => ({...prev, amount: e.target.value}))} 
                  className="border-2 border-gray-300 rounded-xl px-4 py-3 text-lg"
                />
              </div>
              <div className="text-center">
                <button 
                  onClick={addCompany} 
                  className="bg-green-600 text-white px-8 py-3 rounded-xl font-bold text-lg hover:bg-green-700 mr-4"
                >
                  ✅ THÊM
                </button>
                <button 
                  onClick={() => setShowForm(false)} 
                  className="bg-gray-500 text-white px-8 py-3 rounded-xl font-bold text-lg hover:bg-gray-600"
                >
                  ❌ HỦY
                </button>
              </div>
            </div>
          )}

          {/* Companies List */}
          <div className="space-y-6">
            {companies.map(company => (
              <div key={company.id} className="bg-white rounded-2xl shadow-xl p-8">
                <div className="flex justify-between items-center">
                  <div>
                    <h3 className="text-3xl font-bold text-gray-800 mb-2">{company.name}</h3>
                    <p className="text-xl text-gray-600 mb-2">{company.company}</p>
                    <p className="text-4xl font-bold text-blue-600">{company.amount.toLocaleString()} ₫</p>
                  </div>
                  <div className="text-center">
                    <span className={`px-6 py-3 rounded-xl text-xl font-bold ${
                      company.status === 'overdue' 
                        ? 'bg-red-100 text-red-800' 
                        : 'bg-yellow-100 text-yellow-800'
                    }`}>
                      {company.status === 'overdue' ? '🔴 QUÁ HẠN' : '🟡 CHỜ THANH TOÁN'}
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>

        </div>
      </div>
    </>
  )
}
