'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'vi'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Login page
    'login.subtitle': 'AI-Powered Vietnamese Logistics',
    'login.description': 'Advanced logistics management platform with AI-powered route optimization, real-time tracking, and intelligent supply chain solutions for Vietnam market.',
    'login.welcome': 'Welcome Back',
    'login.signInDesc': 'Sign in to access your logistics dashboard',
    'login.email': 'Email Address',
    'login.emailPlaceholder': 'Enter your email address',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.invalidCredentials': 'Invalid credentials. Access denied.',
    'login.authFailed': 'Authentication failed. Please try again.',
    'login.securityNote': 'Your data is protected with enterprise-grade encryption and security measures.',
    'login.features.routing': 'Smart Route Optimization',
    'login.features.routingDesc': 'AI-powered route planning for maximum efficiency',
    'login.features.analytics': 'Advanced Analytics',
    'login.features.analyticsDesc': 'Real-time insights and performance metrics',
    'login.features.vietnam': 'Vietnam Market Focus',
    'login.features.vietnamDesc': 'Specialized for Vietnamese logistics operations',

    // Vietnam Map
    'map.title': 'Vietnam Logistics Map',
    'map.subtitle': 'Explore nationwide logistics network with real-time data and AI analysis',
    'map.search': 'Search & Filter',
    'map.searchProvince': 'Search province/city',
    'map.searchPlaceholder': 'Enter province/city name',
    'map.region': 'Region',
    'map.allRegions': 'All regions',
    'map.north': 'Northern Vietnam',
    'map.central': 'Central Vietnam',
    'map.south': 'Southern Vietnam',
    'map.departure': 'Departure',
    'map.destination': 'Destination',
    'map.selectDeparture': 'Select departure location',
    'map.selectDestination': 'Select destination location',
    'map.calculateRoute': 'Calculate Best Route',
    'map.calculating': 'Calculating optimal route...',
    'map.routeResults': 'Route Calculation Results',
    'map.distance': 'Distance',
    'map.estimatedTime': 'Estimated Time',
    'map.fuelCost': 'Fuel Cost',
    'map.nearestDepot': 'Nearest Depot',
    'map.operationFees': 'Operation Fees',
    'map.totalCost': 'Total Cost',
    'map.selectProvince': 'Select a province',
    'map.selectProvinceDesc': 'Choose a province/city from the list to view detailed information',
    'map.population': 'Population',
    'map.warehouses': 'Warehouses',
    'map.area': 'Area',
    'map.routes': 'Routes',
    'map.monthlyVolume': 'Monthly Volume',
    'map.onTime': 'On Time',
    'map.distributionCenters': 'Distribution Centers',
    'map.economicZones': 'Economic Zones',
    'map.ports': 'Ports',
    'map.airports': 'Airports',

    // Route Optimization
    'route.title': 'AI Route Optimization',
    'route.subtitle': 'Optimize transportation routes with AI to save time, cost and fuel for 40ft containers',
    'route.addPoint': 'Add New Point',
    'route.addPointDesc': 'Add pickup, delivery or warehouse points',
    'route.pointName': 'Point Name',
    'route.pointNamePlaceholder': 'e.g. Tan Binh Warehouse',
    'route.address': 'Address',
    'route.addressPlaceholder': 'e.g. 123 ABC Street, District 1',
    'route.pointType': 'Point Type',
    'route.priority': 'Priority',
    'route.high': 'High',
    'route.medium': 'Medium',
    'route.low': 'Low',
    'route.pickup': 'Pickup',
    'route.delivery': 'Delivery',
    'route.warehouse': 'Warehouse',
    'route.addPointBtn': 'Add Point',
    'route.pointsList': 'Points List',
    'route.clearAll': 'Clear All',
    'route.noPoints': 'No points yet',
    'route.noPointsDesc': 'Add points to start optimization',
    'route.optimizeEngine': 'AI Route Optimization Engine',
    'route.optimizeEngineDesc': 'Use advanced AI algorithms for intelligent route optimization',
    'route.optimizeBtn': 'Optimize Route with AI',
    'route.optimizing': 'Optimizing...',
    'route.needPoints': 'Need at least 2 points to optimize',
    'route.totalDistance': 'Total Distance',
    'route.estimatedTime': 'Estimated Time',
    'route.fuelCost': 'Fuel Cost',
    'route.efficiency': 'Efficiency',
    'route.savings': 'Savings from AI Optimization',
    'route.savedDistance': 'Distance',
    'route.savedTime': 'Time',
    'route.savedFuel': 'Fuel Cost',
    'route.optimizedRoute': 'Optimized Route',
    'route.optimizedRouteDesc': 'Point sequence optimized by AI based on distance, priority and time',
    'route.operatingHours': 'Operating Hours',
    'route.analysisOptimization': 'Optimization Analysis',
    'route.algorithm': 'Algorithm Used',
    'route.algorithmValue': 'AI-Enhanced TSP with priority',
    'route.factors': 'Optimization Factors',
    'route.factorsValue': 'Distance, time, priority',

    // File Learning
    'file.title': 'AI File Learning Engine',
    'file.subtitle': 'Upload and analyze logistics planning files to receive intelligent insights from AI',
    'file.uploadTitle': 'Upload Logistics Planning Files',
    'file.uploadDesc': 'Upload Excel planning files for AI analysis and optimization recommendations',
    'file.dragDrop': 'Drag and drop files or click to select',
    'file.supportedFormats': 'Supported: Excel (.xlsx, .xls), CSV • Max 10MB per file',
    'file.filesUploaded': 'Files uploaded',
    'file.clearAllFiles': 'Clear all',
    'file.processingEngine': 'AI Processing Engine',
    'file.processingDesc': 'Intelligent analysis with machine learning',
    'file.startAnalysis': 'Start AI Analysis',
    'file.analyzing': 'Analyzing with AI...',
    'file.extractData': 'Extract data from Excel',
    'file.analyzePatterns': 'Analyze patterns & trends',
    'file.optimizeRoutes': 'Optimize routes & costs',
    'file.predictDemand': 'Predict future demand',
    'file.downloadResults': 'Download Results',
    'file.analysisOverview': 'Analysis Overview',
    'file.records': 'Records',
    'file.totalCost': 'Total Cost',
    'file.avgDistance': 'Average Distance',
    'file.onTimeDelivery': 'On Time Delivery',
    'file.insights': 'AI Insights & Recommendations',
    'file.processedData': 'Processed Data',
    'file.processedDesc': 'AI has extracted and analyzed records from Excel files',
    'file.date': 'Date',
    'file.route': 'Route',
    'file.vehicle': 'Vehicle',
    'file.driver': 'Driver',
    'file.cargo': 'Cargo',
    'file.status': 'Status',
    'file.cost': 'Cost',
    'file.distance': 'Distance',
    'file.commonRoutes': 'Common Routes',
    'file.showingRecords': 'Showing',
    'file.viewAll': 'View All',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.finish': 'Finish',
    'common.km': 'km',
    'common.hours': 'hours',
    'common.minutes': 'minutes',
    'common.vnd': 'VND',
    'common.tons': 'tons',
  },
  vi: {
    // Login page
    'login.subtitle': 'Logistics Thông Minh Với AI',
    'login.description': 'Nền tảng quản lý logistics tiên tiến với tối ưu hóa tuyến đường AI, theo dõi thời gian thực và giải pháp chuỗi cung ứng thông minh cho thị trường Việt Nam.',
    'login.welcome': 'Chào Mừng Trở Lại',
    'login.signInDesc': 'Đăng nhập để truy cập bảng điều khiển logistics',
    'login.email': 'Địa Chỉ Email',
    'login.emailPlaceholder': 'Nhập địa chỉ email của bạn',
    'login.password': 'Mật Khẩu',
    'login.passwordPlaceholder': 'Nhập mật khẩu của bạn',
    'login.signIn': 'Đăng Nhập',
    'login.signingIn': 'Đang đăng nhập...',
    'login.invalidCredentials': 'Thông tin đăng nhập không hợp lệ. Truy cập bị từ chối.',
    'login.authFailed': 'Xác thực thất bại. Vui lòng thử lại.',
    'login.securityNote': 'Dữ liệu của bạn được bảo vệ bằng mã hóa và các biện pháp bảo mật cấp doanh nghiệp.',
    'login.features.routing': 'Tối Ưu Tuyến Đường Thông Minh',
    'login.features.routingDesc': 'Lập kế hoạch tuyến đường AI để đạt hiệu quả tối đa',
    'login.features.analytics': 'Phân Tích Nâng Cao',
    'login.features.analyticsDesc': 'Thông tin chi tiết và số liệu hiệu suất thời gian thực',
    'login.features.vietnam': 'Tập Trung Thị Trường Việt Nam',
    'login.features.vietnamDesc': 'Chuyên biệt cho hoạt động logistics Việt Nam',

    // Vietnam Map
    'map.title': 'Bản Đồ Logistics Việt Nam',
    'map.subtitle': 'Khám phá mạng lưới logistics toàn quốc với dữ liệu thời gian thực và phân tích AI',
    'map.search': 'Tìm Kiếm & Lọc',
    'map.searchProvince': 'Tìm tỉnh/thành phố',
    'map.searchPlaceholder': 'Nhập tên tỉnh/thành phố',
    'map.region': 'Vùng Miền',
    'map.allRegions': 'Tất cả vùng miền',
    'map.north': 'Miền Bắc',
    'map.central': 'Miền Trung',
    'map.south': 'Miền Nam',
    'map.departure': 'Điểm Khởi Hành',
    'map.destination': 'Điểm Đến',
    'map.selectDeparture': 'Chọn điểm khởi hành',
    'map.selectDestination': 'Chọn điểm đến',
    'map.calculateRoute': 'Tính Tuyến Đường Tối Ưu',
    'map.calculating': 'Đang tính toán tuyến đường tối ưu...',
    'map.routeResults': 'Kết Quả Tính Tuyến Đường',
    'map.distance': 'Khoảng Cách',
    'map.estimatedTime': 'Thời Gian Ước Tính',
    'map.fuelCost': 'Chi Phí Nhiên Liệu',
    'map.nearestDepot': 'Kho Gần Nhất',
    'map.operationFees': 'Phí Vận Hành',
    'map.totalCost': 'Tổng Chi Phí',
    'map.selectProvince': 'Chọn tỉnh/thành phố',
    'map.selectProvinceDesc': 'Chọn một tỉnh/thành phố từ danh sách để xem thông tin chi tiết',
    'map.population': 'Dân Số',
    'map.warehouses': 'Kho Bãi',
    'map.area': 'Diện Tích',
    'map.routes': 'Tuyến Đường',
    'map.monthlyVolume': 'Khối Lượng Tháng',
    'map.onTime': 'Đúng Giờ',
    'map.distributionCenters': 'Trung Tâm Phân Phối',
    'map.economicZones': 'Khu Kinh Tế',
    'map.ports': 'Cảng',
    'map.airports': 'Sân Bay',

    // Route Optimization
    'route.title': 'Tối Ưu Tuyến Đường AI',
    'route.subtitle': 'Tối ưu hóa tuyến đường vận chuyển với AI để tiết kiệm thời gian, chi phí và nhiên liệu cho container 40ft',
    'route.addPoint': 'Thêm Điểm Mới',
    'route.addPointDesc': 'Thêm điểm pickup, giao hàng hoặc kho',
    'route.pointName': 'Tên Điểm',
    'route.pointNamePlaceholder': 'VD: Kho Tân Bình',
    'route.address': 'Địa Chỉ',
    'route.addressPlaceholder': 'VD: 123 Đường ABC, Quận 1',
    'route.pointType': 'Loại Điểm',
    'route.priority': 'Ưu Tiên',
    'route.high': 'Cao',
    'route.medium': 'Trung Bình',
    'route.low': 'Thấp',
    'route.pickup': 'Lấy Hàng',
    'route.delivery': 'Giao Hàng',
    'route.warehouse': 'Kho',
    'route.addPointBtn': 'Thêm Điểm',
    'route.pointsList': 'Danh Sách Điểm',
    'route.clearAll': 'Xóa Tất Cả',
    'route.noPoints': 'Chưa có điểm nào',
    'route.noPointsDesc': 'Thêm điểm để bắt đầu tối ưu',
    'route.optimizeEngine': 'Công Cụ Tối Ưu Tuyến Đường AI',
    'route.optimizeEngineDesc': 'Sử dụng thuật toán AI tiên tiến để tối ưu tuyến đường thông minh',
    'route.optimizeBtn': 'Tối Ưu Tuyến Đường AI',
    'route.optimizing': 'Đang tối ưu hóa...',
    'route.needPoints': 'Cần ít nhất 2 điểm để tối ưu',
    'route.totalDistance': 'Tổng Khoảng Cách',
    'route.estimatedTime': 'Thời Gian Ước Tính',
    'route.fuelCost': 'Chi Phí Nhiên Liệu',
    'route.efficiency': 'Hiệu Quả',
    'route.savings': 'Tiết Kiệm Nhờ AI Optimization',
    'route.savedDistance': 'Khoảng Cách',
    'route.savedTime': 'Thời Gian',
    'route.savedFuel': 'Chi Phí Nhiên Liệu',
    'route.optimizedRoute': 'Tuyến Đường Tối Ưu',
    'route.optimizedRouteDesc': 'Thứ tự điểm đã được AI tối ưu hóa dựa trên khoảng cách, ưu tiên và thời gian',
    'route.operatingHours': 'Giờ Hoạt Động',
    'route.analysisOptimization': 'Phân Tích Tối Ưu Hóa',
    'route.algorithm': 'Thuật Toán Sử Dụng',
    'route.algorithmValue': 'AI-Enhanced TSP với ưu tiên',
    'route.factors': 'Yếu Tố Tối Ưu',
    'route.factorsValue': 'Khoảng cách, thời gian, ưu tiên',

    // File Learning
    'file.title': 'Công Cụ Học File AI',
    'file.subtitle': 'Upload và phân tích các file kế hoạch logistics để nhận insights thông minh từ AI',
    'file.uploadTitle': 'Upload Files Kế Hoạch Logistics',
    'file.uploadDesc': 'Upload các file Excel kế hoạch để AI phân tích và đưa ra khuyến nghị tối ưu',
    'file.dragDrop': 'Kéo thả files hoặc click để chọn',
    'file.supportedFormats': 'Hỗ trợ: Excel (.xlsx, .xls), CSV • Tối đa 10MB mỗi file',
    'file.filesUploaded': 'Files đã upload',
    'file.clearAllFiles': 'Xóa tất cả',
    'file.processingEngine': 'Công Cụ Xử Lý AI',
    'file.processingDesc': 'Phân tích thông minh với machine learning',
    'file.startAnalysis': 'Bắt Đầu Phân Tích AI',
    'file.analyzing': 'Đang phân tích AI...',
    'file.extractData': 'Trích xuất dữ liệu từ Excel',
    'file.analyzePatterns': 'Phân tích patterns & trends',
    'file.optimizeRoutes': 'Tối ưu tuyến đường & chi phí',
    'file.predictDemand': 'Dự đoán nhu cầu tương lai',
    'file.downloadResults': 'Tải Xuống Kết Quả',
    'file.analysisOverview': 'Tổng Quan Phân Tích',
    'file.records': 'Bản Ghi',
    'file.totalCost': 'Tổng Chi Phí',
    'file.avgDistance': 'Khoảng Cách TB',
    'file.onTimeDelivery': 'Giao Đúng Giờ',
    'file.insights': 'AI Insights & Khuyến Nghị',
    'file.processedData': 'Dữ Liệu Đã Xử Lý',
    'file.processedDesc': 'AI đã trích xuất và phân tích bản ghi từ các file Excel',
    'file.date': 'Ngày',
    'file.route': 'Tuyến Đường',
    'file.vehicle': 'Phương Tiện',
    'file.driver': 'Tài Xế',
    'file.cargo': 'Hàng Hóa',
    'file.status': 'Trạng Thái',
    'file.cost': 'Chi Phí',
    'file.distance': 'Khoảng Cách',
    'file.commonRoutes': 'Tuyến Đường Phổ Biến',
    'file.showingRecords': 'Hiển thị',
    'file.viewAll': 'Xem Tất Cả',

    // Common
    'common.loading': 'Đang tải...',
    'common.error': 'Lỗi',
    'common.success': 'Thành công',
    'common.cancel': 'Hủy',
    'common.save': 'Lưu',
    'common.delete': 'Xóa',
    'common.edit': 'Sửa',
    'common.add': 'Thêm',
    'common.search': 'Tìm kiếm',
    'common.filter': 'Lọc',
    'common.clear': 'Xóa',
    'common.close': 'Đóng',
    'common.confirm': 'Xác nhận',
    'common.back': 'Quay lại',
    'common.next': 'Tiếp theo',
    'common.previous': 'Trước',
    'common.finish': 'Hoàn thành',
    'common.km': 'km',
    'common.hours': 'giờ',
    'common.minutes': 'phút',
    'common.vnd': 'VNĐ',
    'common.tons': 'tấn',
  }
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'vi')) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
